# Generated by Django 2.1.7 on 2019-03-13 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
