# Generated by Django 2.1.7 on 2019-03-14 16:52

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=slugger.fields.AutoSlugField(max_length=200, populate_from='title', unique=True),
        ),
    ]
