# Generated by Django 2.1.7 on 2019-03-18 02:27

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File

def import_books(apps, schema_editor):
    """
    Read a CSV file full of books and insert them into the database.
    """
    Book = apps.get_model('bookshelf', 'Book')
    Author = apps.get_model('bookshelf', 'Author')

    Book.objects.all().delete()
    Author.objects.all().delete()
    datapath = os.path.join(settings.BASE_DIR, 'bookshelf/bookshelf_data')
    datafile = os.path.join(datapath, 'books.csv')
    
    with open(datafile) as file:
        reader = csv.DictReader(file) 
        for row in reader:
            #set book_title so that you can only add books that haven't been added
            book_title = row['title']
            author, _ = Author.objects.get_or_create(name=row['author'])
            
            if Book.objects.filter(title=book_title).count():
                return
            #if the title isn't there, make a new book
           
            book = Book(
                title=row['title'],
                description=row['description'],
                url=row['url'],
                category=row['category'],
                created_at=row['date_added'],
                author=author,

            )

            book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_book_category'),
    ]

    operations = [
        migrations.RunPython(import_books)
    ]
